''' Constants related to plotting stuff.
'''

TITLE_SIZE = 16
SMALL_TITLE_SIZE = 14
AXIS_LABELSIZE = 12
AXIS_TICKSIZE = 12
AXIS_SMALLTICKSIZE = 8
DOTSIZE = 6
LEGEND_FONTSIZE = 10
WIDER_DASH = (0, (2, 1))

FIGURE_WIDTH = 7.08 # 180 mm
FIGURE_MAX_HEIGHT = 8.66 # 220 mm
FIGURE_ROW_HEIGHT = 2.5
